spring:
  application:
    name: painel-professores-backend
  datasource:
    url: jdbc:postgresql://localhost:5432/painel_professores
    username: postgres
    password: postgres
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

server:
  port: 8080
